refactor: cleanup e-show
electron/build-tools pull request #319
Opened 2022-01-19 10:30 UTC by codebytere

Miscellaneous cleanup discovered when attempting to write a https://fig.io/ config for `build-tools`

2022-01-19 10:30 UTC, codebytere commented on src/e-show.js
> -  .option('-n, --no-name', "Don't show config name", false)
This was never used.

2022-01-19 10:31 UTC, codebytere commented on src/e-show.js
> +  .option('--gn', 'Show path of the goma.gn file')
I think it's more intuitive to combine these since they're very similar.

2022-01-19 10:32 UTC, codebytere commented on src/e-show.js
> +  .option('--path', 'Output as JSON')
I think it's more intuitive to make showing the `outdir` path an option under `out` 🤔

2022-02-02 22:06 UTC, ckerr approved these changes
These changes make sense to me.

Note, the `e show gomadir`and `e show gomagn` were originally added for https://github.com/electron/build-tools/pull/129 related to https://github.com/electron/electron/pull/22784 for CI. If this is still in use, then @jkleinsc should be aware of this PR. (If it _isn't_ still in use, maybe this section can just be removed?)

Approving because this code is fine, but also req'ing review from John

2022-02-03 17:02 UTC, jkleinsc requested changes
In regards to @ckerr's comment, we never made a change to call `e show gomadir` or `e show gomagn` in CI; we instead directly call:
```
node -e "console.log(require('./src/utils/goma.js').gnFilePath)"
node -e "console.log(require('./src/utils/goma.js').dir)"
```
Marking as request changes as it looks like tests aren't passing

2022-02-07 21:42 UTC, ckerr commented
@jkleinsc requesting re-review, I've fixed up the PR.

changes that I pushed:

- removed `e show gomadir` and `e show gomagn` based on John's comment above
- fixed `e show out` 
- updated tests to use the new `--filepath` parameter
- restored `e show current`'s output format and the `--no-name` option so tests can query the config filename

2022-02-08 16:53 UTC, jkleinsc approved these changes

2022-02-08 17:02 UTC, merged