docs: added section on e load-xcode and how to fix security error
electron/build-tools pull request #444
Opened 2022-12-20 17:16 UTC by mccare

I was running into error when `e init` was downloading and installing Xcode.app. The error was pretty confusing, so I tried to document it in the Readme. 

<img width="389" alt="Screenshot 2022-12-20 at 18 10 55" src="https://user-images.githubusercontent.com/2522744/208726544-d5ff816f-57f0-438d-b61f-4fe7324ae672.png">
<img width="263" alt="Screenshot 2022-12-20 at 18 10 59" src="https://user-images.githubusercontent.com/2522744/208726547-209e039d-2aec-4f4e-959a-38527eb585b1.png">
<img width="707" alt="Screenshot 2022-12-20 at 18 11 12" src="https://user-images.githubusercontent.com/2522744/208726548-63b08210-63e0-49ea-b48d-1da606621b56.png">

2023-05-03 13:26 UTC, codebytere commented on README.md
> +
Let's not add this extra space here please!

2023-05-03 13:26 UTC, codebytere commented on README.md
> +`e load-xcode` downloads and unpacks Xcode and required macOS SDK into the electron buildtools (`.electron_build_tools`) directory
Space between header and top description please!

2023-05-03 13:26 UTC, codebytere commented on README.md
> +In case you get a pop up saying that "Xcode is damaged", you need to acknowledge the dialog with cancel and open it through system preferences. Go to System Preferences/Security & Privacy. There will
Let's tweak the wording of this:

>  As of some more recent Xcode releases, you may see a popup dialog saying "Xcode is damaged". If this occurs, you will need to acknowledge the dialog with cancel and open it through macOS System Preferences. Go to the `Security & Privacy` section within System Preferences. There will be a section stating "Xcode is from an unidentified developer". Press "Open Anyway" to acknowledge that you want to open `Xcode.app`. Following this, run the `e load-xcode` command again to verify it works as expected.
```

2023-06-05 00:01 UTC, MarshallOfSound requested changes
This doesn't show up on M1 based macs and isn't the correct solution afaik.  Folks need to add their terminal application (normally Terminal or iTerm to the list of Developer Tools in their privacy settings on their mac)

2023-06-06 23:29 UTC, mccare commented
Good point, I'm using Kitty.app and it is not listed in my developer tools. So this is pretty specific to my setup and doesn't warrant more documentation. Feel free to close it.

2023-06-08 10:37 UTC, closed without merging