fix: show e-depot-tools command output on Windows
electron/build-tools pull request #563
Opened 2024-02-26 15:43 UTC by codebytere

Closes https://github.com/electron/build-tools/issues/562.

2024-02-26 22:35 UTC, ckerr approved these changes

2024-02-26 23:02 UTC, MarshallOfSound commented
`shell: true` was added to fix python3 issues a while back https://github.com/electron/build-tools/pull/391 we should make sure we aren't making that worse

cc @dsanders11

2024-03-01 22:46 UTC, dsanders11 requested changes
I can't seem to repro #562 on my machine - I get the expected output?

`shell: true` is necessary otherwise you have to explicitly put `.bat` extensions to run them. Testing on this branch, I actually can't run `e d gn --help` with these changes:

```shell
Running "gn --help"
ERROR Failed to run command:
 Error: spawnSync gn ENOENT
```

@codebytere, can you provide more environment details that might shine some light on the issue? I'm testing on Windows 10, Node.js 16/18/20 and don't see it.

2024-04-13 14:53 UTC, codebytere commented
@dsanders11 sorry i abandoned this but: I was running git bash in Windows 11.

2024-06-26 07:53 UTC, closed without merging